update docker

diff --git a/DockerFile b/DockerFile
--- a/DockerFile
+++ b/DockerFile
@@ -1,45 +1,92 @@
-# ---------- base ----------
-FROM node:20-slim AS base
+FROM node:20-alpine AS base
 
-# ---------- builder ----------
-FROM base AS builder
+# Install dependencies only when needed
+FROM base AS deps
+# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
+RUN apk add --no-cache libc6-compat
 WORKDIR /app
 
-COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
-
+COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* .npmrc* ./
 RUN \
   if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
   elif [ -f package-lock.json ]; then npm ci; \
-  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i; \
-  else npm install; \
+  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i --frozen-lockfile; \
+  else echo "Lockfile not found." && exit 1; \
   fi
 
-COPY . .
+# Step 1. Rebuild the source code only when needed
+FROM base AS builder
 
-ARG NEXT_PUBLIC_API_URL
-ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
-
-RUN npm run build
-
-
-# ---------- runner ----------
-FROM base AS runner
 WORKDIR /app
 
-RUN groupadd -r nodejs && useradd -r -g nodejs nextjs
+COPY --from=deps /app/node_modules ./node_modules
+COPY . .
 
-# ✅ create writable dirs FIRST
-RUN mkdir -p /app/cache /app/tmp \
-    && chown -R nextjs:nodejs /app
+# Environment variables must be present at build time
+# https://github.com/vercel/next.js/discussions/14030
+ARG NEXT_PUBLIC_API_URL
+ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
 
-ENV NEXT_CACHE_DIR=/app/cache
-ENV TMPDIR=/app/tmp
+ARG NEXT_PUBLIC_LOGO_URL
+ENV NEXT_PUBLIC_LOGO_URL=${NEXT_PUBLIC_LOGO_URL}
+
+ARG NEXT_PUBLIC_KODE_OPD
+ENV NEXT_PUBLIC_KODE_OPD=${NEXT_PUBLIC_KODE_OPD}
+
+ARG NEXT_PUBLIC_NAMA_APLIKASI
+ENV NEXT_PUBLIC_NAMA_APLIKASI=${NEXT_PUBLIC_NAMA_APLIKASI}
+
+ARG NEXT_PUBLIC_NAMA_PEMDA
+ENV NEXT_PUBLIC_NAMA_PEMDA=${NEXT_PUBLIC_NAMA_PEMDA}
+
+# Next.js collects completely anonymous telemetry data about general usage. Learn more here: https://nextjs.org/telemetry
+# Uncomment the following line to disable telemetry at build time
 ENV NEXT_TELEMETRY_DISABLED=1
 
+# Build Next.js based on the preferred package manager
+RUN \
+  if [ -f yarn.lock ]; then yarn build; \
+  elif [ -f package-lock.json ]; then npm run build; \
+  elif [ -f pnpm-lock.yaml ]; then pnpm build; \
+  else npm run build; \
+  fi
+
+# Step 2. Production image, copy all the files and run next
+FROM base AS runner
+
+WORKDIR /app
+
+# Don't run production as root
+RUN addgroup --system --gid 1001 nodejs
+RUN adduser --system --uid 1001 nextjs
 USER nextjs
 
-COPY --from=builder --chown=nextjs:nodejs /app/public ./public
+COPY --from=builder /app/public ./public
+
+# Automatically leverage output traces to reduce image size
+# https://nextjs.org/docs/advanced-features/output-file-tracing
 COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
 COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
 
-CMD ["node","server.js"]
+# Environment variables must be redefined at run time
+ARG NEXT_PUBLIC_API_URL
+ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
+
+ARG NEXT_PUBLIC_LOGO_URL
+ENV NEXT_PUBLIC_LOGO_URL=${NEXT_PUBLIC_LOGO_URL}
+
+ARG NEXT_PUBLIC_KODE_OPD
+ENV NEXT_PUBLIC_KODE_OPD=${NEXT_PUBLIC_KODE_OPD}
+
+ARG NEXT_PUBLIC_NAMA_APLIKASI
+ENV NEXT_PUBLIC_NAMA_APLIKASI=${NEXT_PUBLIC_NAMA_APLIKASI}
+
+ARG NEXT_PUBLIC_NAMA_PEMDA
+ENV NEXT_PUBLIC_NAMA_PEMDA=${NEXT_PUBLIC_NAMA_PEMDA}
+
+# Uncomment the following line to disable telemetry at run time
+ENV NEXT_TELEMETRY_DISABLED=1
+
+# Note: Don't expose ports here, Compose will handle that for us
+
+CMD ["node", "server.js"]
